---
title: "Dependent T-test"
author: "William W. Lage"
date: "8/14/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#setup
```{r library}
library(jmv) #contains our t-test, descriptives, and non-core functions
library(data.table) #for optional melt function
```

```{r import data}
Wave1 <- read.csv("Wave1.csv")
Wave4 <- read.csv("wave4.csv")
```

```{r combine the dataframes}
#For those familiar with SQL, this is the equivalent of joining tables but using an all join rather than a left or right join. Both are however available in this function by replacing "all" with "all.x" (left) or "all.y" (right). 

#for more information enter ??data.table::merge into the console

data<- merge(Wave1,Wave4[,c("AID","WEIGHT")], by="AID", all = TRUE)
```

```{r recoding and renaming}
#renaming columns using their index positions
names(data)[3:4] <- c("WEIGHT1", "WEIGHT4")

#Like the independent t-test demo we have some values which the codebook identifies as non-values
data$WEIGHT1[data$WEIGHT1=="996"]<-"NA"
data$WEIGHT1[data$WEIGHT1=="998"]<-"NA"
data$WEIGHT1[data$WEIGHT1=="999"]<-"NA"
data$WEIGHT4[data$WEIGHT4=="996"]<-"NA"
data$WEIGHT4[data$WEIGHT4=="998"]<-"NA"
#convert the two columns back to integers coercing the NA's into non-string values
data$WEIGHT1 <- as.integer(data$WEIGHT1)
data$WEIGHT4 <- as.integer(data$WEIGHT4)

#remove the SEX column because it is not relevant to our hypothesis
data2 <- data[, -c(2)]

#and of course, check your work
str(data2)
```
#cleaning and initial descriptives
```{r initial descriptives}
desc <- descriptives(data2, vars = c('WEIGHT1', 'WEIGHT4'), hist = TRUE, sd = TRUE, se = TRUE, skew = TRUE, kurt = TRUE)
desc
```
```{r cleaning}
#remove NA's
data.noNA <- na.omit(data2)

#While not a statistical assumption for dependent t-test, we know some of the values are off so we're going to remove them
##identify univariate outliers
data.noNA[abs(scale(data.noNA$WEIGHT1)) > 3, ]
data.noNA[abs(scale(data.noNA$WEIGHT4)) > 3, ]
##remove the univeriate outliers
data.noUni <- data.noNA[!abs(scale(data.noNA$WEIGHT1)) > 3, ]
data.noUni <- data.noUni[!abs(scale(data.noUni$WEIGHT4)) > 3, ]
```

#final descriptives and t-test
```{r normality of difference}
data.noUni$diff <- (data.noUni$WEIGHT4 - data.noUni$WEIGHT1)

desc <- descriptives(data.noUni, vars = c('diff'), hist = TRUE, sd = TRUE, se = TRUE, skew = TRUE, kurt = TRUE)
desc
```

```{r paired samples T-test}
ttestPS(data = data.noUni, pairs = list(list(i1='WEIGHT1', i2='WEIGHT4')), effectSize = TRUE, ci = TRUE, desc = TRUE)
```

#visualization 1 - bar graphs showing mean weight at each point
```{r visual library}
library(ggplot2) #for visuals
```

```{r wide to long}
#the visualization here works better if your data is in long form with different time points represented by different labels in a column. So this is how you shift your data to make multiple columns into one.

data.long <- reshape(data = data.noUni,                      #data set
                        idvar='AID',                        #id variable
                        varying=c('WEIGHT1','WEIGHT4'),     #repeated measures variables
                        times=c(1,2),                       #time metric/occasion variable
                        v.names='WEIGHT',                   #name of consolidated column
                        direction='long')                   #long or wide depending on needs

#alternatively, the melt function is less code intense, but I find reshape to be more versatile
#data.l = melt(data = data.noNA, id.vars = c("AID"), measure.vars = c("WEIGHT1", "WEIGHT4"))
```

```{r}
library(ggplot2)
ggplot(data.long, aes(x = factor(time), y = WEIGHT))+
  stat_summary(fun.y = mean,
               geom = "col",
               fill = "forestgreen")+
  stat_summary(fun.data = mean_se,           #use mean_sdl if you want SD error bars
               fun.args = list(mult = 1),    #number of intervals from the fun.data center
               geom = "errorbar")+
  ggtitle("Weight at Different Waves")+      #label your plot
  labs(x = "Wave", y = "Weight (lbs)")       #label your axis
```

#visualization 2: graph of linear change for participants
```{r linear graph}
#for clarity you can subset the data using the function below:
wght_long1 <- data.long[which(data.long$AID > 55000000 & data.long$AID < 60000000), ]

#creating a plot and assigning it to an object 
plot_obs <- ggplot(data=wght_long1,                        #new subset, or full with data.long
                   aes(x=time, y=WEIGHT, group=AID)) +    #calling variables
                   geom_line() +                          #adding lines to plot
                   theme_bw() +                           #changing style/background
                   scale_x_continuous(breaks = c(1,2), name = "wave") +   #creating breaks in the x-axis and labeling the x-axis
                   scale_y_continuous(breaks = c(0,50,100,150,200,250,300,350,400), name = "Weight") #creating breaks in the y-axis and labeling the y-axis

#printing the object (plot)
print(plot_obs)
```
