---
title: "Longitudinal Analysis"
author: "William W. Lage"
date: "4/27/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(readr)
library(reshape)
library(tidyverse)
```
#data prep
```{r import data}
Deaths <- read_csv("DeathW.csv")
Cases <- read_csv("casesW.csv")
Population <- read_csv("covid_county_population_usafacts.csv")
Beds <- read_csv("Beds2.csv")
```
```{r all things equal}
#I'm not including the cruise ship into California as it increases cases without relevant population
Cases2 <- Cases[-c(193),]
Population2 <- Population[-c(193),]
Deaths2 <- Deaths[-c(193),]

#get rid of columns we're not using
Beds2 <- Beds[,-c(6,7)]

#introducing ID variables. These IDs only line up because we already verified that the dataframes lined up.
id <- seq(1, nrow(Cases2))
Cases2$ID <- id
Deaths2$ID <- id
Beds2$ID <- id
Population2$ID <- id
```

```{r tidyverse}
dat2 <- merge(Population2, Beds2, by = "ID", all = TRUE)
dat3 <- dat2 [,c(1,2,3,9,4,5,10,11)]
dat4 <- merge(dat3, Deaths2, by = "ID", all = TRUE)
dat5 <- dat4 [,-c(9:12)]
dat6 <- reshape(data = dat5,
                        idvar='ID',
                        varying=c('deaths1','deaths2','deaths3','deaths4','deaths5','deaths6','deaths7','deaths8','deaths9','deaths10','deaths11','deaths12','deaths13','deaths14','deaths15','deaths16','deaths17','deaths18','deaths19','deaths20','deaths21','deaths22','deaths23','deaths24','deaths25','deaths26','deaths27','deaths28','deaths29','deaths30','deaths31','deaths32','deaths33','deaths34','deaths35','deaths36','deaths37','deaths38','deaths39','deaths40','deaths41','deaths42','deaths43','deaths44','deaths45','deaths46','deaths47','deaths48','deaths49','deaths50','deaths51','deaths52','deaths53','deaths54','deaths55','deaths56','deaths57','deaths58','deaths59','deaths60','deaths61','deaths62','deaths63','deaths64','deaths65','deaths66','deaths67','deaths68','deaths69','deaths70','deaths71','deaths72','deaths73','deaths74','deaths75','deaths76','deaths77','deaths78','deaths79','deaths80','deaths81','deaths82','deaths83','deaths84','deaths85','deaths86','deaths87','deaths88','deaths89','deaths90','deaths91','deaths92','deaths93'),
                        times=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93),
                        v.names='deaths',                                            
                        direction='long') 
Cases2 <- Cases2[,c(98,1:97)]
Cases3 <- gather (Cases2, key = "time", value = "cases", -ID, -countyFIPS, -"County Name", -State, -stateFIPS)
dat7 <- merge(dat6, Cases3, all =  TRUE)
LongF <- dat7 [,c(1,3:9,2,15,10)]
Long0<-LongF[!(LongF$population=="0"),]
```

```{r wide}
Wide <- merge(dat4,Cases2,by="ID", all = TRUE)
WideF <- Wide[, -c(9:12,106:109)]
colnames(WideF)[2]<- "countyFIPS"
colnames(WideF)[3]<- "county name"
colnames(WideF)[5]<- "state"
#get rid of empty places
Wide0<-WideF[!(WideF$population=="0"),]
```

```{r desc}
library(jmv)
desc_full <- descriptives(data = Long0, 
                        vars = c('population','ICU Beds','Percent of Population Aged 60+','cases', 'deaths'), 
                        sd = TRUE, 
                        skew = TRUE, 
                        kurt = TRUE,
                        hist = TRUE)
desc_full
boxplot(Long0$population, horizontal = TRUE)
quantile(Long0$population, na.rm = TRUE)

```

```{r corr}
#creating a function that will plot bivariate relationships of our variables
panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col="cyan", ...)
}
pairs(Long0[6:11], 
      diag.panel=panel.hist)
Corr2 <- round(cor(Long0 [,-c(1:5,9)]), 2)
Corr2
```
```{r visual 1}
library(ggplot2)
#creating a plot and assigning it to an object 
plot_obs <- ggplot(data=Long0,
                   aes(x=time, y=cases, group=ID)) +                                                   #calling variables
                   geom_line() +                                                                     #adding lines to plot
                   theme_bw() +                                                                      #changing style/background
                   scale_x_continuous(breaks = c(0,10,20,30,40,50,60,70,80,90), name = "days") +   #creating breaks in the x-axis and labeling the x-axis
                   scale_y_continuous(breaks = c(0,5000,10000,15000,20000,25000,30000,35000,40000,45000,50000), name = "Cases") #creating breaks in the y-axis and labeling the y-axis

#printing the object (plot)
print(plot_obs)
```
#linear analysis
```{r lme}
#NLME had an error. Good thign we have a back-up
library(lme4)
#fitting no growth model and assigning it to an object
ng.lmer <- lmer(deaths ~ 1 + (1 | ID), 
                     data = Long0, 
                     REML = FALSE,
                     na.action = "na.exclude")

#obtaining summary of the model using the object we just created  
summary(ng.lmer)
```
```{r gm death no var}
library(nlme)
#fitting linear growth model and assigning it to an object
lg.death.nlme <- nlme(deaths~(beta_1+d_1i)+(beta_2+d_2i)*(time),  
                   data=Long0,                      
                   fixed=beta_1+beta_2~1,                      
                   random=d_1i+d_2i~1,
                   group=~ID,                     
                   start=c(beta_1=0,beta_2=0),
                   na.action = "na.exclude")

#obtaining summary of the model using the object we just created
summary (lg.death.nlme)
```
```{r quad no var}

#model did not converge in 50 iterations, so we're adjusting
lmeCtlList <- lmeControl(maxIter = 500, msMaxIter = 200, tolerance = 1e-4, niter = 100,
                         msTol = 1e-5, nlmStepMax = 500, 
                         msVerbose = FALSE,
                         returnObject = TRUE)

quad.nlme <- nlme(deaths~b_1i+b_2i*(time)+b_3i*(time)^2,
                      data=Long0,
                      fixed=b_1i+b_2i+b_3i~1,
                      random=b_1i+b_2i+b_3i~1,
                      groups=~ID,
                      start=c(0, 0, 0),
                      na.action=na.exclude,
                  control=lmeCtlList)
summary(quad.nlme) 
```
#time invariant models
```{r gm only SES}
population <- nlme(deaths ~ (beta_01 + beta_11*(population/10000) + d_1i) +
                      (beta_02 + beta_12*(population/10000) + d_2i)*(time) +
                      (beta_03 + beta_13*(population/10000) + d_3i)*(time)^2,
        data=Long0,
        fixed=beta_01+beta_11+beta_02+beta_12+beta_03+beta_13~1,
        random=d_1i+d_2i+d_3i~1,
        group=~ID,
        start=c(beta_01=0, beta_11=0, beta_02=0, beta_12=0, beta_03=0, beta_13=0),
        na.action=na.exclude,
        control = lmeCtlList)
summary(population)
```
#cases
```{r gm death no var}
library(nlme)
#fitting linear growth model and assigning it to an object
lg.death.nlme <- nlme(cases~(beta_1+d_1i)+(beta_2+d_2i)*(time),  
                   data=Long0,                      
                   fixed=beta_1+beta_2~1,                      
                   random=d_1i+d_2i~1,
                   group=~ID,                     
                   start=c(beta_1=0,beta_2=0),
                   na.action = "na.exclude")

#obtaining summary of the model using the object we just created
summary (lg.death.nlme)
```
```{r quad no var}

#model did not converge in 50 iterations, so we're adjusting
lmeCtlList <- lmeControl(maxIter = 500, msMaxIter = 200, tolerance = 1e-4, niter = 100,
                         msTol = 1e-5, nlmStepMax = 500, 
                         msVerbose = FALSE,
                         returnObject = TRUE)

quad.nlme <- nlme(cases~b_1i+b_2i*(time)+b_3i*(time)^2,
                      data=Long0,
                      fixed=b_1i+b_2i+b_3i~1,
                      random=b_1i+b_2i+b_3i~1,
                      groups=~ID,
                      start=c(0, 0, 0),
                      na.action=na.exclude,
                  control=lmeCtlList)
summary(quad.nlme) 
```
##time invariant models
```{r gm Cases:Pop}
population2 <- nlme(cases ~ (beta_01 + beta_11*(population/10000) + d_1i) +
                      (beta_02 + beta_12*(population/10000) + d_2i)*(time) +
                      (beta_03 + beta_13*(population/10000) + d_3i)*(time)^2,
        data=Long0,
        fixed=beta_01+beta_11+beta_02+beta_12+beta_03+beta_13~1,
        random=d_1i+d_2i+d_3i~1,
        group=~ID,
        start=c(beta_01=0, beta_11=0, beta_02=0, beta_12=0, beta_03=0, beta_13=0),
        na.action=na.exclude,
        control = lmeCtlList)
summary(population2)
```

#Cross-Validation Approach
##Remaking Cases
```{r wide cases}
#variables names caused an issue for cases in lavaan because they're all numbers rather than names
CasesN <- read_csv("casesW2.csv")
CasesN2 <- CasesN[-c(193),]
CasesN2$ID <- id
CasesN2 <- CasesN2[,c(98,1:97)]
CasesN3 <- merge(dat3, CasesN2, by = "ID", all = TRUE)
CasesN4 <- CasesN3 [,-c(9:12)]
CasesW<-CasesN4[!(CasesN4$population=="0"),]
```
```{r partitioning}
library(caret)
training_index <- createDataPartition(CasesW$cases93, p=0.80, list=FALSE)
ctrain <-CasesW[training_index,]
ctest <- CasesW[-training_index,]
```
#Lavaan
```{r make the model}
library(lavaan)
Quad_model <- '
#intercept factor loadings
eta_1 =~ 1*cases71 + 
         1*cases72 + 
         1*cases73 + 
         1*cases74 + 
         1*cases75 + 
         1*cases76 + 
         1*cases77 + 
         1*cases78 + 
         1*cases79

#linear change factor loadings
eta_2 =~ -1.4167*cases71 +
         -1.25  *cases72 +
         -1     *cases73 +
         -0.75  *cases74 +
         -0.5   *cases75 +
         -0.25  *cases76 +
          0     *cases77 +
          0.5   *cases78 +
          1.5   *cases79

#quadratic change factor loadings
eta_3 =~ 2.1169*cases71 +
         1.5625*cases72 +
         1     *cases73 +
         0.5625*cases74 +
         0.25  *cases75 +
         0.0625 *cases76 +
         0     *cases77 +
         0.25  *cases78 +
         2.25  *cases79

#manifest variances to be same over time
cases71 ~~ theta*cases71
cases72 ~~ theta*cases72
cases73 ~~ theta*cases73
cases74 ~~ theta*cases74
cases75 ~~ theta*cases75
cases76 ~~ theta*cases76
cases77 ~~ theta*cases77
cases78 ~~ theta*cases78
cases79 ~~ theta*cases79

#latent variances
eta_1 ~~ eta_1
eta_2 ~~ eta_2
eta_3 ~~ eta_3

#latent covariances
eta_1 ~~ eta_2
eta_1 ~~ eta_3
eta_2 ~~ eta_3
#latent means
eta_1 ~ start(65)*1*65
eta_2 ~ start(2)*1
eta_3 ~ start(0.1)*1

#manifest means fixed to 0
cases71 ~ 0*1
cases72 ~ 0*1
cases73 ~ 0*1
cases74 ~ 0*1
cases75 ~ 0*1
cases76 ~ 0*1
cases77 ~ 0*1
cases78 ~ 0*1
cases79 ~ 0*1
'
```

```{r model fit}
quad_fit <- sem(Quad_model, data = Wide0, meanstructure = T, mimic="mplus")
summary(quad, fit.measures = T, standardized = T)
```